### ISSUE TITLE
Not able to install through yum.

### ISSUE THREAD

**Issue by munib-rehman** [GetPageSpeed/ngx_security_headers#10]
Hi.
I'm not able to install it using yum although yum is working on my server. it says unable to open....
is there any other way i can download and install the module.
thanks logs are below:
sudo yum -y install https://extras.getpagespeed.com/release-latest.rpm
**Failed to set locale, defaulting to C
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Cannot open: https://extras.getpagespeed.com/release-latest.rpm. Skipping.
Error: Nothing to do**

**Comment by dvershinin** [comment]
This only means that your system's clock is incorrect. It must be well synchronized and have a proper time set, in order to verify the SSL certificate.
Fix your system by [enabling NTP synchronization](https://www.getpagespeed.com/server-setup/configure-time-rhel#enable-ntp).
