### ISSUE TITLE
X-XSS-Protection: 0 is recommended by Mozilla and Google

### ISSUE THREAD

**Issue by DavidOsipov** [GetPageSpeed/ngx_security_headers#19]
Currently, [Mozilla](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection)  and [Google](https://chromestatus.com/feature/5021976655560704) do not recommend setting X-XSS-Protection to enabled state due to the fact that the XSS auditor can even create new XSS vulnerabilities in otherwise secure websites. `X-XSS-Protection: 0 `is preferred.

**Comment by dvershinin** [comment]
I'm not sure what would be the best to do here:

> Setting the X-XSS-Protection header to either 0 or 1; mode=block prevents vulnerabilities like the one described above

... while bringing back XSS vulnerability from having disabled XSS filtering. Then for best security, it would be sending `1; mode=block` as they suggest.

> These protections are largely unnecessary in modern browsers when sites implement a strong [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) that disables the use of inline JavaScript ('unsafe-inline').

Perhaps a better option would be sending `X-XSS-Protection: 0` only if `Content-Security-Policy` is set in the response? (always sending either `0` or `1; mode=block` doesn't seem like a great default).

**Comment by DavidOsipov** [comment]
Dead weight issue - closing.
