### ISSUE TITLE
Rewrite Referrer-Policy header

### ISSUE THREAD

**Issue by fersm** [GetPageSpeed/ngx_security_headers#2]
How about, before anything else this module is great.

Is there any way to overwrite the Referrer-Policy header?

I have seen that this module adds the header with the default "no-referrer-when-downgrade" and if I add the add_header instruction with the value "no-referrer" two headers with different values are added.

**Comment by dvershinin** [comment]
I've put up a new release for this: you can use [new directive](https://github.com/GetPageSpeed/ngx_security_headers#security_headers_referrer_policy) for controlling the same in favor of `add_header`.

Example:

```
security_headers_referrer_policy unsafe-url;
```
Note that the new default value is `strict-origin-when-cross-origin`.

In case you want the module not to tinker with this header at all, use `omit`:

```
security_headers_referrer_policy omit;
```

**Comment by fersm** [comment]
Thank you very much for the quick answer. I will be testing the changes you have made.
