### ISSUE TITLE
Missing ".configure" file for compiling on Ubuntu

### ISSUE THREAD

**Issue by Danrancan** [GetPageSpeed/ngx_security_headers#20]
The compile on other platforms module states the following:
```
./configure --with-compat --add-module=../ngx_security_headers
make 
make install
```

However, I am trying to compile this module on Ubuntu Server, but there is no .configure file in the root directory, so the `./configure --with-compat --add-module=../ngx_security_headers` command doesn't work. How am I supposed to configure this module and compile it? Please help.

**Comment by dvershinin** [comment]
The `configure` file is part of NGINX sources, you must run the command in the extracted directory of NGINX source tarball/zip. And `--add-module=../ngx_security_headers` assumes the module source files are one directory level up from those.
