### ISSUE TITLE
not find ngx_http_security_headers_module.so

### ISSUE THREAD

**Issue by bidianqing** [GetPageSpeed/ngx_security_headers#8]
I'm use the link install nginx on centos 7 https://nginx.org/en/linux_packages.html#RHEL-CentOS  
use the follow command install ngx_security_headers 
```
sudo yum -y install https://extras.getpagespeed.com/release-latest.rpm
sudo yum -y install nginx-module-security-headers
```
I'm not find the ngx_http_security_headers_module.so file

**Comment by dvershinin** [comment]
You need to have an [active subscription](https://www.getpagespeed.com/repo-subscribe) to the repository, then run the above commands.
